import { Currency } from "lucide-react";

export const packageData = [
    {
        id: 1,
        name: "Basic",
        disk: "10GB",
        bandwidth: "100GB",
        cpu: "1 Core",
        ram: "1GB",
        currency: "BDT",
        offerPrice: 500,
        price: 1000,
        currentPackage: true,
        recommended: false,
    },
    {
        id: 2,
        name: "Standard",
        disk: "20GB",
        bandwidth: "200GB",
        cpu: "2 Core",
        ram: "2GB",
        currency: "BDT",
        offerPrice: 1500,
        price: 2000,
        currentPackage: false,
        recommended: false,
    },
    {
        id: 3,
        name: "Premium",
        disk: "30GB",
        bandwidth: "300GB",
        cpu: "3 Core",
        ram: "3GB",
        currency: "BDT",
        offerPrice: 2500,
        price: 3000,
        currentPackage: false,
        recommended: false,
    },
    {
        id: 4,
        name: "Ultimate",
        disk: "40GB",
        bandwidth: "400GB",
        cpu: "4 Core",
        ram: "4GB",
        currency: "BDT",
        offerPrice: 3500,
        price: 4000,
        currentPackage: false,
        recommended: false,
    },
    {
        id: 5,
        name: "Enterprise",
        disk: "50GB",
        bandwidth: "500GB",
        cpu: "5 Core",
        ram: "5GB",
        currency: "USD",
        offerPrice: 4500,
        price: 5000,
        currentPackage: false,
        recommended: true,
    },
    {
        id: 6,
        name: "Business",
        disk: "60GB",
        bandwidth: "600GB",
        cpu: "6 Core",
        ram: "6GB",
        currency: "USD",
        offerPrice: 5500,
        price: 6000,
        currentPackage: false,
        recommended: true,
    },
    {
        id: 7,
        name: "Corporate",
        disk: "70GB",
        bandwidth: "700GB",
        cpu: "7 Core",
        ram: "7GB",
        currency: "USD",
        offerPrice: 6500,
        price: 7000,
        currentPackage: false,
        recommended: true,
    }
]