export type TEmailUser = {
  id: number;
  type: string;
  displayName: string;
  username: string;
  loginUserUid: string;
  loginPassword: string;
  primaryEmailId: number;
  primaryPhoneId: number;
  primaryProjectId: number;
  sex: string;
  dobLong: number;
  dobString: string;
  avatar: string;
  starId: number;
  suspensionReason: string;
  lastLogin: number;
  isTwoFaEnabled: boolean;
  source: string;
  sourceUrl: string;
  status: string;
  creator: number;
  ipString: string;
  timeCreated: number;
  timeUpdated: number;
  timeDeleted: number;
  photoUrl: string;
};
export type TUserAddressItem = {
  city: string;
  country: string;
  email: string;
  fax: string;
  id: number;
  isPrimary: number;
  line1: string;
  line2: string;
  line3: string;
  mobile: string;
  name: string;
  organization: string;
  state: string;
  status: string;
  telephone: string;
  zipCode: string;
  photoUrl: string;
  user: TEmailUser;
};

export type TAddAddress = {
  userId: number;
  email: string;
};
